#!/usr/bin/env python3.10

from coordinates import get_coordinates
from weather_api_service import get_weather
from weather_formatter import format_weather
from exceptions import CantGetLocationInfo, ApiServiceError


def main():
    try:
        coordinates = get_coordinates()
    except CantGetLocationInfo:
        print("Failed to get GPS coordinates")
        exit(1)
    try:
        weather = get_weather(coordinates)
    except ApiServiceError:
        print(f"Failed to get the weather by coordinates {coordinates}.")
        exit(1)
    print(format_weather(weather))


if __name__ == '__main__':
    main()
